<?php
declare(strict_types=1);

// Testfälle (werden von tests/run.php eingebunden; $base, Client, check(), same(), section() stehen dort bereit).
$year = date('Y');
$A = new Client($base);
$B = new Client($base);
$anon = new Client($base);

function acct(Client $c, string $number): array
{
    foreach ($c->get('/accounting/accounts?kind=all&limit=2000')['rows'] as $a) if ($a['number'] === $number) return $a;
    throw new RuntimeException("Konto $number fehlt");
}
function bal(Client $c, string $number): int { return (int) acct($c, $number)['balance_cents']; }

section('Sicherheit und Anmeldung');
[$s] = $anon->call('GET', '/customers');
same($s, 401, 'ohne Login kein Zugriff');
same($anon->get('/auth/me')['user'], null, 'Sitzungsprüfung ohne Login liefert keinen Benutzer');
[$s] = $anon->call('POST', '/auth/login', ['email' => 'x@y.de', 'password' => 'egal'], ['X-Requested-With' => 'other']);
check($s === 403 || $s === 401, 'falscher X-Requested-With wird abgelehnt', $s);
$ch = curl_init("$base/api/auth/login");
curl_setopt_array($ch, [CURLOPT_POST => true, CURLOPT_POSTFIELDS => '{}', CURLOPT_RETURNTRANSFER => true, CURLOPT_HTTPHEADER => ['Content-Type: application/json']]);
curl_exec($ch);
same((int) curl_getinfo($ch, CURLINFO_HTTP_CODE), 403, 'POST ohne X-Requested-With (CSRF) → 403');
curl_close($ch);
[$s] = $anon->call('POST', '/auth/login', ['email' => 'x@y.de', 'password' => 'egal'], ['Origin' => 'https://evil.example']);
same($s, 403, 'fremder Origin → 403');
$anon->fails('POST', '/auth/signup', ['company' => 'X GmbH', 'name' => 'A', 'email' => 'a@x.de', 'password' => 'kurz1'], 400, 'zu kurzes Passwort');
$anon->fails('POST', '/auth/signup', ['company' => 'X GmbH', 'name' => 'A', 'email' => 'keine-mail', 'password' => 'LangesPasswort123'], 400, 'ungültige E-Mail');
$me = $A->ok('POST', '/auth/signup', ['company' => 'Test Handel GmbH', 'name' => 'Anna Admin', 'email' => 'anna@test-handel.de', 'password' => 'GeheimesPasswort42']);
same($me['user']['role'], 'admin', 'Registrierung macht Administrator');
same($me['tenant']['plan'], 'starter', 'Starter-Tarif');
check(in_array('admin:w', $me['perms'], true), 'Administrator hat alle Rechte');
$A->fails('POST', '/auth/signup', ['company' => 'Zweite', 'name' => 'A', 'email' => 'ANNA@test-handel.de', 'password' => 'GeheimesPasswort42'], 409, 'E-Mail doppelt (Groß/Klein egal)');
same($A->get('/auth/me')['user']['email'], 'anna@test-handel.de', 'Sitzung bleibt über Cookie bestehen');
$t2 = new Client($base);
$t2->fails('POST', '/auth/login', ['email' => 'anna@test-handel.de', 'password' => 'falsch'], 401, 'falsches Passwort');
$t2->ok('POST', '/auth/login', ['email' => 'anna@test-handel.de', 'password' => 'GeheimesPasswort42']);
same($t2->get('/auth/me')['tenant']['name'], 'Test Handel GmbH', 'Login funktioniert');
$brute = new Client($base);
for ($i = 0; $i < 5; $i++) $brute->call('POST', '/auth/login', ['email' => 'opfer@test-handel.de', 'password' => 'x' . $i]);
$brute->fails('POST', '/auth/login', ['email' => 'opfer@test-handel.de', 'password' => 'x6'], 429, 'Anmeldeversuche werden begrenzt');
$t2->ok('POST', '/auth/logout');
[$s] = $t2->call('GET', '/customers');
same($s, 401, 'Abmelden beendet die Sitzung');

section('Stammdaten: Kunden, Lieferanten, Artikel, Lager');
$sup = $A->ok('POST', '/suppliers', ['name' => 'Papier Großhandel AG', 'email' => 'verkauf@papier.de', 'street' => 'Hafenstr. 1', 'zip' => '20457', 'city' => 'Hamburg', 'payment_days' => 30, 'lead_days' => 5, 'iban' => 'DE89 3704 0044 0532 0130 00']);
same($sup['number'], '70001', 'erster Lieferant bekommt Kreditorenkonto 70001');
$cust = $A->ok('POST', '/customers', ['name' => 'Musterkunde GmbH', 'email' => 'einkauf@musterkunde.de', 'street' => 'Marktplatz 5', 'zip' => '80331', 'city' => 'München', 'payment_days' => 14, 'tags' => 'Stammkunde']);
same($cust['number'], '10001', 'erster Kunde bekommt Debitorenkonto 10001');
$cust2 = $A->ok('POST', '/customers', ['name' => 'Zweitkunde e.K.', 'status' => 'lead']);
same($cust2['number'], '10002', 'zweiter Kunde 10002');
$A->fails('POST', '/customers', ['name' => ''], 400, 'Kunde ohne Namen');
$A->fails('POST', '/customers', ['name' => 'X', 'email' => 'kaputt'], 400, 'Kunde mit ungültiger E-Mail');
$A->ok('POST', "/customers/{$cust['id']}/contacts", ['name' => 'Erika Muster', 'role' => 'Einkauf', 'email' => 'erika@musterkunde.de', 'is_primary' => true]);
$act = $A->ok('POST', "/customers/{$cust['id']}/activities", ['kind' => 'task', 'text' => 'Angebot nachfassen', 'due_date' => date('Y-m-d', strtotime('-1 day'))]);
$detail = $A->get("/customers/{$cust['id']}");
same(count($detail['contacts']), 1, 'Ansprechpartner gespeichert');
same(count($detail['activities']), 1, 'Aktivität gespeichert');
check(count($A->get('/activities')['rows']) === 1, 'offene Aufgabe erscheint in der Aufgabenliste');
$A->ok('PUT', "/activities/{$act['id']}", ['done' => true]);
same(count($A->get('/activities')['rows']), 0, 'erledigte Aufgabe verschwindet');
same(count($A->get('/customers?q=muster')['rows']), 1, 'Suche findet Kunden (Name/E-Mail)');
same(count($A->get('/customers?q=kunde')['rows']), 2, 'Suche findet beide Kunden');
same(count($A->get('/customers?status=lead')['rows']), 1, 'Filter nach Status');

$wh1 = $A->get('/warehouses')['rows'][0];
same($wh1['code'], 'HL', 'Hauptlager vorhanden');
$wh2 = $A->ok('POST', '/warehouses', ['name' => 'Außenlager', 'code' => 'w2']);
$A->fails('POST', '/warehouses', ['name' => 'Doppelt', 'code' => 'HL'], 409, 'Lagerkürzel doppelt');
$p1 = $A->ok('POST', '/products', ['sku' => 'KP-80', 'name' => 'Kassenrolle 80 mm', 'price_cents' => 500, 'cost_cents' => 200, 'tax_rate' => 19, 'track_stock' => true, 'min_stock' => 10, 'supplier_id' => $sup['id'], 'weight_g' => 120, 'category' => 'Verbrauch']);
$p2 = $A->ok('POST', '/products', ['sku' => 'SUP-1', 'name' => 'Support-Stunde', 'unit' => 'Std', 'price_cents' => 12000, 'tax_rate' => 19, 'track_stock' => false]);
$p3 = $A->ok('POST', '/products', ['sku' => 'BR-1', 'name' => 'Brötchen', 'price_cents' => 100, 'cost_cents' => 40, 'tax_rate' => 7, 'track_stock' => true, 'supplier_id' => $sup['id']]);
$A->fails('POST', '/products', ['sku' => 'KP-80', 'name' => 'Doppelt'], 409, 'Artikelnummer doppelt');
$A->fails('POST', '/products', ['sku' => 'X', 'name' => 'Falsche Steuer', 'tax_rate' => 21], 400, 'ungültiger Steuersatz');
$A->fails('POST', '/products', ['sku' => 'Y', 'name' => 'Fremder Lieferant', 'supplier_id' => 99999], 400, 'unbekannter Lieferant');

section('Einkauf: Bestellung, Wareneingang, Eingangsrechnung, Zahlung');
$po = $A->ok('POST', '/purchasing/orders', ['supplier_id' => $sup['id'], 'warehouse_id' => $wh1['id'], 'lines' => [['product_id' => $p1['id'], 'qty' => 100], ['product_id' => $p3['id'], 'qty' => 50]]]);
$poD = $A->get("/purchasing/orders/{$po['id']}");
same($poD['status'], 'draft', 'Bestellung startet als Entwurf');
same($poD['net_cents'], 22000, 'Bestellung netto (Einkaufspreise aus Artikel)');
same($poD['tax_cents'], 3940, 'Bestellung Steuer (3800 + 140)');
same($poD['gross_cents'], 25940, 'Bestellung brutto');
$A->fails('POST', "/purchasing/orders/{$po['id']}/receive", ['warehouse_id' => $wh1['id'], 'lines' => []], 409, 'Wareneingang vor Bestellung nicht möglich');
$A->ok('POST', "/purchasing/orders/{$po['id']}/order");
$lines = $A->get("/purchasing/orders/{$po['id']}")['lines'];
$A->ok('POST', "/purchasing/orders/{$po['id']}/receive", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $lines[0]['id'], 'qty' => 60]]]);
same($A->get("/purchasing/orders/{$po['id']}")['status'], 'partial', 'Teillieferung → teilweise geliefert');
$A->fails('POST', "/purchasing/orders/{$po['id']}/receive", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $lines[0]['id'], 'qty' => 41]]], 409, 'mehr als offen liefern');
$A->ok('POST', "/purchasing/orders/{$po['id']}/receive", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $lines[0]['id'], 'qty' => 40], ['line_id' => $lines[1]['id'], 'qty' => 50]]]);
same($A->get("/purchasing/orders/{$po['id']}")['status'], 'received', 'vollständig geliefert');
$st = $A->get('/stock');
$row1 = current(array_filter($st['rows'], fn($x) => $x['sku'] === 'KP-80'));
same($row1['total'], 100.0, 'Bestand Kassenrolle nach Wareneingang');
same($row1['value_cents'], 20000, 'Lagerwert = 100 × 2,00 €');
$A->fails('POST', "/purchasing/orders/{$po['id']}/cancel", null, 409, 'Bestellung mit Wareneingang nicht stornierbar');

$inv = ['supplier_id' => $sup['id'], 'po_id' => $po['id'], 'supplier_ref' => 'LR-4711', 'date' => "$year-01-15", 'lines' => [
    ['description' => 'Kassenrolle', 'qty' => 100, 'net_cents' => 20000, 'tax_rate' => 19, 'po_line_id' => $lines[0]['id']],
    ['description' => 'Brötchen', 'qty' => 50, 'net_cents' => 2000, 'tax_rate' => 7, 'po_line_id' => $lines[1]['id']]]];
$si = $A->ok('POST', '/purchasing/invoices', $inv);
$A->fails('POST', '/purchasing/invoices', $inv, 409, 'Eingangsrechnung doppelt erfassen');
$siD = $A->get("/purchasing/invoices/{$si['id']}");
same($siD['gross_cents'], 25940, 'Eingangsrechnung brutto');
same($siD['due_date'], date('Y-m-d', strtotime("$year-01-15 +30 days")), 'Fälligkeit aus Zahlungsziel des Lieferanten (30 Tage)');
same($A->get("/purchasing/orders/{$po['id']}")['status'], 'completed', 'Bestellung ist komplett (geliefert und abgerechnet)');
same(bal($A, '3400'), 20000, 'Buchung: Wareneingang 19 %');
same(bal($A, '3300'), 2000, 'Buchung: Wareneingang 7 %');
same(bal($A, '1576'), 3800, 'Buchung: Vorsteuer 19 %');
same(bal($A, '1571'), 140, 'Buchung: Vorsteuer 7 %');
same(bal($A, '70001'), -25940, 'Kreditorenkonto: Verbindlichkeit');
$A->ok('POST', "/purchasing/invoices/{$si['id']}/payments", ['amount_cents' => 10000, 'date' => "$year-02-01"]);
same($A->get("/purchasing/invoices/{$si['id']}")['status'], 'partial', 'Teilzahlung → teilweise bezahlt');
$A->fails('POST', "/purchasing/invoices/{$si['id']}/payments", ['amount_cents' => 15941], 409, 'Überzahlung abgelehnt');
$A->ok('POST', "/purchasing/invoices/{$si['id']}/payments", ['amount_cents' => 15940, 'date' => "$year-02-10"]);
same($A->get("/purchasing/invoices/{$si['id']}")['status'], 'paid', 'Eingangsrechnung bezahlt');
same(bal($A, '70001'), 0, 'Kreditorenkonto ausgeglichen');
same(bal($A, '1200'), -25940, 'Bank nach Zahlungen');
$A->fails('POST', "/purchasing/invoices/{$si['id']}/cancel", null, 409, 'bezahlte Rechnung nicht stornierbar');

section('Verkauf: Angebot → Auftrag → Lieferschein → Rechnung → Zahlung');
$q = $A->ok('POST', '/sales/quotes', ['customer_id' => $cust['id'], 'lines' => [
    ['product_id' => $p1['id'], 'qty' => 30, 'discount_pct' => 10], ['product_id' => $p2['id'], 'qty' => 2], ['product_id' => $p3['id'], 'qty' => 10]]]);
$qD = $A->get("/sales/quotes/{$q['id']}");
same($qD['net_cents'], 38500, 'Angebot netto (Rabatt 10 % auf Zeile 1)');
same($qD['tax_cents'], 7195, 'Angebot Steuer (19 %: 7125 + 7 %: 70)');
same($qD['gross_cents'], 45695, 'Angebot brutto');
check(str_contains($qD['bill_to'], 'Musterkunde GmbH') && str_contains($qD['bill_to'], '80331 München'), 'Rechnungsadresse aus Kundendaten');
$A->ok('POST', "/sales/quotes/{$q['id']}/status", ['status' => 'sent']);
$ord = $A->ok('POST', "/sales/quotes/{$q['id']}/convert");
same($A->get("/sales/quotes/{$q['id']}")['status'], 'converted', 'Angebot wurde übernommen');
$A->fails('POST', "/sales/quotes/{$q['id']}/convert", null, 409, 'Angebot nicht zweimal übernehmen');
$oD = $A->get("/sales/orders/{$ord['id']}");
same($oD['gross_cents'], 45695, 'Auftrag übernimmt Summen');
same($oD['status'], 'open', 'Auftrag offen');
$st = $A->get('/stock');
same(current(array_filter($st['rows'], fn($x) => $x['sku'] === 'KP-80'))['reserved'], 30.0, 'Auftrag reserviert Ware');
same(current(array_filter($st['rows'], fn($x) => $x['sku'] === 'KP-80'))['available'], 70.0, 'verfügbar = Bestand − Reservierung');
$ol = $oD['lines'];
$A->fails('POST', "/sales/orders/{$ord['id']}/deliver", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $ol[1]['id'], 'qty' => 1]]], 400, 'Dienstleistung wird nicht geliefert');
$A->fails('POST', "/sales/orders/{$ord['id']}/deliver", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $ol[0]['id'], 'qty' => 31]]], 409, 'mehr als bestellt liefern');
$del = $A->ok('POST', "/sales/orders/{$ord['id']}/deliver", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $ol[0]['id'], 'qty' => 20]]]);
check(str_starts_with($del['number'], "LS-$year-"), 'Lieferschein-Nummer', $del);
same($A->get("/sales/orders/{$ord['id']}")['status'], 'partial', 'Auftrag teilgeliefert');
$st = $A->get('/stock');
$kp = current(array_filter($st['rows'], fn($x) => $x['sku'] === 'KP-80'));
same($kp['total'], 80.0, 'Bestand nach Lieferung');
same($kp['reserved'], 10.0, 'Reservierung sinkt auf den Rest');

$invDraft = $A->ok('POST', "/sales/orders/{$ord['id']}/invoice");
$idD = $A->get("/sales/invoices/{$invDraft['id']}");
same($idD['status'], 'draft', 'Rechnung ist zuerst ein Entwurf');
same($idD['number'], null, 'Entwurf hat noch keine Nummer');
same($idD['net_cents'], 33000, 'Rechnung: gelieferte Ware (20 × 4,50 €) + Dienstleistung');
same($idD['gross_cents'], 39270, 'Rechnung brutto');
$A->fails('POST', "/sales/orders/{$ord['id']}/invoice", null, 409, 'nichts mehr abzurechnen');
$iss = $A->ok('POST', "/sales/invoices/{$invDraft['id']}/issue", ['date' => "$year-03-01"]);
same($iss['number'], "RE-$year-00001", 'erste Rechnungsnummer');
$idD = $A->get("/sales/invoices/{$invDraft['id']}");
same($idD['status'], 'open', 'Rechnung offen');
same($idD['due_date'], date('Y-m-d', strtotime("$year-03-01 +14 days")), 'Fälligkeit aus Kunden-Zahlungsziel');
$A->fails('PUT', "/sales/invoices/{$invDraft['id']}", ['customer_id' => $cust['id'], 'lines' => [['description' => 'x', 'qty' => 1, 'price_cents' => 1]]], 409, 'ausgestellte Rechnung ist unveränderlich');
$A->fails('DELETE', "/sales/invoices/{$invDraft['id']}", null, 409, 'ausgestellte Rechnung nicht löschbar');
same(bal($A, '10001'), 39270, 'Debitorenkonto: Forderung');
same(bal($A, '8400'), -33000, 'Erlöse 19 %');
same(bal($A, '1776'), -6270, 'Umsatzsteuer 19 %');
$p = $A->ok('POST', "/sales/invoices/{$invDraft['id']}/payments", ['amount_cents' => 20000, 'date' => "$year-03-10", 'method' => 'bank']);
same($A->get("/sales/invoices/{$invDraft['id']}")['status'], 'partial', 'Teilzahlung');
$A->fails('POST', "/sales/invoices/{$invDraft['id']}/payments", ['amount_cents' => 19271], 409, 'Überzahlung der Kundenrechnung');
$p2pay = $A->ok('POST', "/sales/invoices/{$invDraft['id']}/payments", ['amount_cents' => 19270, 'date' => "$year-03-11"]);
same($A->get("/sales/invoices/{$invDraft['id']}")['status'], 'paid', 'Rechnung bezahlt');
$A->ok('POST', "/payments/{$p2pay['id']}/reverse");
$idD = $A->get("/sales/invoices/{$invDraft['id']}");
same($idD['status'], 'partial', 'Zahlungsstorno öffnet die Rechnung wieder');
same($idD['paid_cents'], 20000, 'bezahlter Betrag nach Storno');
$A->fails('POST', "/payments/{$p2pay['id']}/reverse", null, 409, 'Zahlung nicht zweimal stornieren');
same(bal($A, '10001'), 19270, 'Forderung nach Zahlungsstorno');

section('Gutschrift, Retoure, Direktrechnung');
$invLines = $idD['lines'];
$A->fails('POST', "/sales/invoices/{$invDraft['id']}/credit-note", ['lines' => [['line_id' => $invLines[0]['id'], 'qty' => 21]]], 409, 'mehr gutschreiben als berechnet');
$cn = $A->ok('POST', "/sales/invoices/{$invDraft['id']}/credit-note", ['lines' => [['line_id' => $invLines[0]['id'], 'qty' => 5]], 'restock_warehouse_id' => $wh1['id'], 'reason' => 'Retoure beschädigt']);
same($cn['number'], "GS-$year-00001", 'Gutschrift-Nummer');
$cnD = $A->get("/sales/credit-notes/{$cn['id']}");
same($cnD['net_cents'], 2250, 'Gutschrift netto');
same($cnD['tax_cents'], 428, 'Steuer wird kaufmännisch gerundet (427,5 → 428)');
$idD = $A->get("/sales/invoices/{$invDraft['id']}");
same($idD['credited_cents'], 2678, 'gutgeschriebener Betrag an der Rechnung');
same($idD['open_cents'], 16592, 'offener Betrag nach Gutschrift');
$kp = current(array_filter($A->get('/stock')['rows'], fn($x) => $x['sku'] === 'KP-80'));
same($kp['total'], 85.0, 'Retoure bucht Ware zurück ins Lager');
$A->ok('POST', "/sales/invoices/{$invDraft['id']}/payments", ['amount_cents' => 16592, 'date' => "$year-04-01"]);
same($A->get("/sales/invoices/{$invDraft['id']}")['status'], 'paid', 'Rest bezahlt');
same(bal($A, '10001'), 0, 'Debitorenkonto ausgeglichen (Rechnung − Gutschrift − Zahlungen)');

$direct = $A->ok('POST', '/sales/invoices', ['customer_id' => $cust['id'], 'lines' => [['product_id' => $p3['id'], 'qty' => 5]]]);
$A->fails('POST', "/sales/invoices/{$direct['id']}/issue", null, 400, 'Direktrechnung braucht ein Lager für den Warenausgang');
$A->ok('PUT', "/sales/invoices/{$direct['id']}", ['customer_id' => $cust['id'], 'warehouse_id' => $wh1['id'], 'lines' => [['product_id' => $p3['id'], 'qty' => 5]]]);
$iss2 = $A->ok('POST', "/sales/invoices/{$direct['id']}/issue");
same($iss2['number'], "RE-$year-00002", 'Rechnungsnummern laufen lückenlos weiter');
$br = current(array_filter($A->get('/stock')['rows'], fn($x) => $x['sku'] === 'BR-1'));
same($br['total'], 45.0, 'Direktrechnung bucht Ware aus dem Lager');
$big = $A->ok('POST', '/sales/invoices', ['customer_id' => $cust['id'], 'warehouse_id' => $wh1['id'], 'lines' => [['product_id' => $p3['id'], 'qty' => 500]]]);
$r = $A->fails('POST', "/sales/invoices/{$big['id']}/issue", null, 409, 'zu wenig Bestand');
check(str_contains($r['error'] ?? '', 'Nicht genug Bestand'), 'Fehlermeldung nennt den Bestand', $r);
same($A->get("/sales/invoices/{$big['id']}")['status'], 'draft', 'fehlgeschlagene Ausstellung lässt den Entwurf unverändert');
$A->ok('DELETE', "/sales/invoices/{$big['id']}");
$A->fails('POST', '/sales/invoices', ['customer_id' => $cust['id'], 'lines' => []], 400, 'Beleg ohne Positionen');
$A->fails('POST', '/sales/invoices', ['customer_id' => 999999, 'lines' => [['description' => 'x', 'qty' => 1, 'price_cents' => 100]]], 400, 'Beleg für unbekannten Kunden');

section('Aufträge stornieren, Lieferung rückgängig, Logistik');
$o2 = $A->ok('POST', '/sales/orders', ['customer_id' => $cust['id'], 'lines' => [['product_id' => $p1['id'], 'qty' => 1000]]]);
$o2l = $A->get("/sales/orders/{$o2['id']}")['lines'];
$A->fails('POST', "/sales/orders/{$o2['id']}/deliver", ['warehouse_id' => $wh1['id'], 'lines' => [['line_id' => $o2l[0]['id'], 'qty' => 1000]]], 409, 'Lieferung ohne ausreichenden Bestand');
$A->ok('POST', "/sales/orders/{$o2['id']}/cancel");
same($A->get("/sales/orders/{$o2['id']}")['status'], 'cancelled', 'Auftrag storniert');
$o3 = $A->ok('POST', '/sales/orders', ['customer_id' => $cust['id'], 'lines' => [['product_id' => $p1['id'], 'qty' => 4]]]);
$o3l = $A->get("/sales/orders/{$o3['id']}")['lines'];
$d3 = $A->ok('POST', "/sales/orders/{$o3['id']}/deliver", ['warehouse_id' => $wh1['id'], 'create_shipment' => true, 'lines' => [['line_id' => $o3l[0]['id'], 'qty' => 4]]]);
check($d3['shipment_id'] > 0, 'Lieferung legt auf Wunsch eine Sendung an');
$A->fails('POST', "/sales/orders/{$o3['id']}/cancel", null, 409, 'Auftrag mit Lieferung nicht stornierbar');
$A->ok('POST', "/sales/deliveries/{$d3['id']}/cancel");
$kp = current(array_filter($A->get('/stock')['rows'], fn($x) => $x['sku'] === 'KP-80'));
same($kp['total'], 85.0, 'Lieferschein-Storno bucht Ware zurück');
same($A->get("/sales/orders/{$o3['id']}")['status'], 'open', 'Auftrag wieder offen nach Lieferschein-Storno');
same($A->get("/logistics/shipments/{$d3['shipment_id']}")['status'], 'cancelled', 'Sendung zum stornierten Lieferschein ist storniert');
$A->ok('POST', "/sales/orders/{$o3['id']}/cancel");

$o4 = $A->ok('POST', '/sales/orders', ['customer_id' => $cust['id'], 'lines' => [['product_id' => $p1['id'], 'qty' => 2]]]);
$o4l = $A->get("/sales/orders/{$o4['id']}")['lines'];
$carriers = $A->get('/logistics/carriers')['rows'];
$dhl = current(array_filter($carriers, fn($x) => $x['name'] === 'DHL'));
$d4 = $A->ok('POST', "/sales/orders/{$o4['id']}/deliver", ['warehouse_id' => $wh1['id'], 'create_shipment' => true, 'carrier_id' => $dhl['id'], 'tracking_no' => 'JJD0123 45', 'lines' => [['line_id' => $o4l[0]['id'], 'qty' => 2]]]);
$sh = $A->get("/logistics/shipments/{$d4['shipment_id']}");
same($sh['status'], 'planned', 'Sendung geplant');
same($sh['weight_g'], 240, 'Gewicht aus Artikeln (2 × 120 g)');
same($sh['track_link'], 'https://www.dhl.de/de/privatkunden/pakete-empfangen/verfolgen.html?piececode=JJD0123%2045', 'Tracking-Link mit maskierter Sendungsnummer');
$A->ok('PUT', "/logistics/shipments/{$sh['id']}", ['carrier_id' => $dhl['id'], 'tracking_no' => 'JJD012345', 'eta' => date('Y-m-d', strtotime('-1 day')), 'packages' => 1, 'weight_g' => 240, 'cost_cents' => 495]);
$A->ok('POST', "/logistics/shipments/{$sh['id']}/status", ['status' => 'shipped', 'note' => 'Abholung durch DHL']);
$sh = $A->get("/logistics/shipments/{$sh['id']}");
same($sh['ship_date'], date('Y-m-d'), 'Versanddatum wird gesetzt');
same($sh['late'], true, 'überfällige Sendung wird markiert');
same(count($sh['events']), 2, 'Statusverlauf wird protokolliert');
$A->ok('POST', "/logistics/shipments/{$sh['id']}/status", ['status' => 'delivered']);
$A->fails('POST', "/logistics/shipments/{$sh['id']}/status", ['status' => 'in_transit'], 409, 'zugestellte Sendung nicht zurücksetzen');
$A->fails('POST', '/logistics/carriers', ['name' => 'Böse', 'tracking_url' => 'javascript:alert(1)//{tracking}'], 400, 'gefährlicher Tracking-Link');
$A->fails('POST', '/logistics/carriers', ['name' => 'Unsicher', 'tracking_url' => 'http://x.de/{tracking}'], 400, 'Tracking-Link nur mit https');
$A->ok('POST', '/logistics/carriers', ['name' => 'Hermes', 'tracking_url' => 'https://example.org/t/{tracking}']);
$inb = $A->ok('POST', '/logistics/shipments', ['direction' => 'inbound', 'po_id' => $po['id'], 'carrier_id' => $dhl['id'], 'tracking_no' => 'IN1']);
same($A->get("/logistics/shipments/{$inb['id']}")['party_name'], 'Papier Großhandel AG', 'Eingangssendung übernimmt den Lieferanten');
$cnts = $A->get('/logistics/shipments')['counts'];
check(($cnts['delivered'] ?? 0) === 1 && ($cnts['cancelled'] ?? 0) === 1, 'Sendungsstatus-Zähler', $cnts);

section('Lager: Umlagerung, Korrektur, Inventur, Nachbestellung');
$A->ok('POST', '/stock/transfer', ['product_id' => $p1['id'], 'from_warehouse_id' => $wh1['id'], 'to_warehouse_id' => $wh2['id'], 'qty' => 10]);
$kp = current(array_filter($A->get('/stock')['rows'], fn($x) => $x['sku'] === 'KP-80'));
same($kp['levels'][$wh2['id']]['qty'], 10.0, 'Umlagerung: Zielbestand');
same($kp['levels'][$wh1['id']]['qty'], 73.0, 'Umlagerung: Quellbestand (85 − 2 geliefert − 10)');
$A->fails('POST', '/stock/transfer', ['product_id' => $p1['id'], 'from_warehouse_id' => $wh2['id'], 'to_warehouse_id' => $wh1['id'], 'qty' => 11], 409, 'Umlagerung über den Bestand');
$A->fails('POST', '/stock/transfer', ['product_id' => $p1['id'], 'from_warehouse_id' => $wh1['id'], 'to_warehouse_id' => $wh1['id'], 'qty' => 1], 400, 'gleiches Lager');
$A->fails('POST', '/stock/adjust', ['product_id' => $p1['id'], 'warehouse_id' => $wh1['id'], 'delta' => -3], 400, 'Korrektur braucht einen Grund');
$A->ok('POST', '/stock/adjust', ['product_id' => $p1['id'], 'warehouse_id' => $wh1['id'], 'delta' => -3, 'reason' => 'Bruch']);
$A->fails('POST', '/stock/adjust', ['product_id' => $p2['id'], 'warehouse_id' => $wh1['id'], 'delta' => 1, 'reason' => 'x'], 400, 'Dienstleistung hat keinen Bestand');
$inv1 = $A->ok('POST', '/inventory', ['warehouse_id' => $wh2['id']]);
$A->fails('POST', '/inventory', ['warehouse_id' => $wh2['id']], 409, 'zweite offene Inventur im selben Lager');
$iv = $A->get("/inventory/{$inv1['id']}");
$ivl = current(array_filter($iv['lines'], fn($x) => $x['sku'] === 'KP-80'));
same((float) $ivl['expected'], 10.0, 'Inventur: Sollbestand');
$A->ok('PUT', "/inventory/{$inv1['id']}", ['lines' => [['id' => $ivl['id'], 'counted' => 8]]]);
$fin = $A->ok('POST', "/inventory/{$inv1['id']}/finish");
same($fin['differences'], 1, 'Inventur bucht genau die gezählte Differenz');
$kp = current(array_filter($A->get('/stock')['rows'], fn($x) => $x['sku'] === 'KP-80'));
same($kp['levels'][$wh2['id']]['qty'], 8.0, 'Inventur: neuer Bestand');
$A->fails('POST', "/inventory/{$inv1['id']}/finish", null, 409, 'Inventur nicht zweimal abschließen');
same(count($A->get('/purchasing/reorder')['rows']), 0, 'keine Nachbestellung bei ausreichendem Bestand');
$pp = $A->get("/products/{$p1['id']}")['item'];
$A->ok('PUT', "/products/{$p1['id']}", ['sku' => 'KP-80', 'name' => 'Kassenrolle 80 mm', 'price_cents' => 500, 'cost_cents' => 200, 'tax_rate' => 19, 'track_stock' => true, 'min_stock' => 500, 'reorder_qty' => 100, 'supplier_id' => $sup['id']]);
$re = $A->get('/purchasing/reorder')['rows'];
check(count($re) === 1 && $re[0]['sku'] === 'KP-80', 'Nachbestell-Vorschlag bei Unterbestand', $re);
same($re[0]['suggest_qty'], 600.0 - $re[0]['available'] < 1 ? 1.0 : ceil(600 - $re[0]['available']), 'Vorschlagsmenge füllt auf Mindestbestand + Nachbestellmenge auf');
$ro = $A->ok('POST', '/purchasing/reorder/create', ['items' => [['product_id' => $p1['id'], 'qty' => $re[0]['suggest_qty']]]]);
same(count($ro['ids']), 1, 'Nachbestellung legt Bestellentwurf an');
$A->fails('DELETE', "/products/{$p1['id']}", null, 409, 'verwendeter Artikel nicht löschbar');

section('Buchhaltung: Journal, Eigene Konten, Auswertungen');
$bank = $A->ok('POST', '/accounting/finance-accounts', ['kind' => 'bank', 'name' => 'Sparkasse Geschäftskonto', 'iban' => 'DE89370400440532013000', 'opening_cents' => 100000, 'opening_date' => "$year-01-01"]);
same($bank['number'], '1201', 'zweites Bankkonto bekommt 1201');
$cash = acct($A, '1000');
$A->ok('POST', '/accounting/transfer', ['from_account_id' => $bank['id'], 'to_account_id' => $cash['id'], 'amount_cents' => 20000, 'date' => "$year-05-01"]);
same(bal($A, '1201'), 80000, 'Umbuchung: Bank');
same(bal($A, '1000'), 20000, 'Umbuchung: Kasse');
$A->fails('POST', '/accounting/transfer', ['from_account_id' => $bank['id'], 'to_account_id' => $bank['id'], 'amount_cents' => 1], 400, 'Umbuchung auf dasselbe Konto');
$A->ok('POST', '/accounting/private', ['type' => 'withdrawal', 'account_id' => $cash['id'], 'amount_cents' => 5000, 'date' => "$year-05-02"]);
same(bal($A, '1800'), 5000, 'Privatentnahme');
same(bal($A, '1000'), 15000, 'Kasse nach Privatentnahme');
$fa = $A->get('/accounting/finance-accounts');
same($fa['total_cents'], 80000 + 15000 + (-25940 + 20000 + 16592), 'Summe der eigenen Konten (Sparkasse + Kasse + Bank 1200 mit Kundenzahlungen)');
$office = acct($A, '4930');
$bad = ['date' => "$year-06-01", 'text' => 'Büromaterial', 'lines' => [['account_id' => $office['id'], 'debit_cents' => 1000], ['account_id' => $cash['id'], 'credit_cents' => 900]]];
$A->fails('POST', '/accounting/journal', $bad, 400, 'unausgeglichene Buchung wird abgelehnt');
$bad['lines'][1]['credit_cents'] = 1000;
$mj = $A->ok('POST', '/accounting/journal', $bad);
check(str_starts_with($mj['number'], "BU-$year-"), 'Buchungsnummer', $mj);
$A->fails('POST', '/accounting/journal', ['date' => "$year-06-01", 'text' => 'x', 'lines' => [['account_id' => acct($A, '10001')['id'], 'debit_cents' => 100], ['account_id' => $cash['id'], 'credit_cents' => 100]]], 400, 'Personenkonten nicht manuell bebuchen');
$A->fails('POST', '/accounting/journal', ['date' => "$year-06-01", 'text' => 'x', 'lines' => [['account_id' => $office['id'], 'debit_cents' => 100, 'credit_cents' => 100]]], 400, 'Zeile mit Soll und Haben');
$A->ok('POST', "/accounting/journal/{$mj['id']}/reverse");
same(bal($A, '4930'), 0, 'Storno gleicht die Buchung aus');
$A->fails('POST', "/accounting/journal/{$mj['id']}/reverse", null, 409, 'Buchung nicht zweimal stornieren');
$invEntry = null;
foreach ($A->get("/accounting/journal?source=invoice")['rows'] as $e) $invEntry = $e;
$A->fails('POST', "/accounting/journal/{$invEntry['id']}/reverse", null, 409, 'Rechnungsbuchung nur über Gutschrift stornierbar');
$A->ok('PUT', '/settings', ['company_name' => 'Test Handel GmbH', 'books_closed_until' => "$year-06-30"]);
$A->fails('POST', '/accounting/journal', ['date' => "$year-06-15", 'text' => 'zu spät', 'lines' => [['account_id' => $office['id'], 'debit_cents' => 100], ['account_id' => $cash['id'], 'credit_cents' => 100]]], 409, 'Buchung in festgeschriebenem Zeitraum');
$A->ok('POST', '/accounting/journal', ['date' => "$year-07-01", 'text' => 'nach Festschreibung', 'lines' => [['account_id' => $office['id'], 'debit_cents' => 100], ['account_id' => $cash['id'], 'credit_cents' => 100]]]);
$A->ok('PUT', '/settings', ['books_closed_until' => null]);

$tb = $A->get("/reports/trial-balance?from=$year-01-01&to=$year-12-31&detail=1");
same($tb['totals']['debit_cents'], $tb['totals']['credit_cents'], 'Summen- und Saldenliste: Soll = Haben');
same($tb['totals']['closing_cents'], 0, 'Summen- und Saldenliste: alle Salden zusammen 0');
$bs = $A->get("/reports/balance-sheet?to=$year-12-31");
same($bs['assets_total_cents'], $bs['passiva_total_cents'], 'Bilanz: Aktiva = Passiva');
$pnl = $A->get("/reports/pnl?from=$year-01-01&to=$year-12-31");
same($pnl['revenue_total_cents'], 33000 - 2250 + 500, 'GuV: Erlöse (Rechnungen − Gutschrift)');
same($pnl['result_cents'], $bs['result_cents'], 'GuV-Ergebnis = Ergebnis in der Bilanz');
$vat = $A->get("/reports/vat?from=$year-01-01&to=$year-12-31");
same($vat['output_total_cents'], (6270 - 428) + 35, 'USt-Voranmeldung: Umsatzsteuer');
same($vat['input_total_cents'], 3940, 'USt-Voranmeldung: Vorsteuer');
same($vat['payable_cents'], 5877 - 3940, 'USt-Voranmeldung: Zahllast');
$led = $A->get('/accounting/accounts/' . acct($A, '10001')['id'] . '/ledger');
same($led['closing_cents'], 535, 'Kontoblatt Debitor: Endsaldo (nur die Direktrechnung ist offen)');
check(count($led['rows']) >= 5, 'Kontoblatt enthält Rechnung, Zahlungen, Storno, Gutschrift', count($led['rows']));
$stmt = $A->get("/customers/{$cust['id']}/statement");
same($stmt['ledger']['closing_cents'], 535, 'Kundenkonto-Auszug: Direktrechnung offen (5 × 1,00 € + 7 %)');
same(count($stmt['open_items']), 1, 'Offene Posten des Kunden');
$ar = $A->get('/accounting/open-items?type=debtors');
same($ar['total_cents'], 535, 'Offene Posten Debitoren (Summe)');
$ap = $A->get('/accounting/open-items?type=creditors');
same($ap['total_cents'], 0, 'Offene Posten Kreditoren (alles bezahlt)');
$sales = $A->get("/reports/sales?by=customer&from=$year-01-01&to=$year-12-31");
same($sales['total_net_cents'], 33000 - 2250 + 500, 'Verkaufsauswertung nach Kunde');
same($A->get("/reports/sales?by=product&from=$year-01-01&to=$year-12-31")['total_net_cents'], 31250, 'Verkaufsauswertung nach Artikel');
$dash = $A->get('/reports/dashboard');
same($dash['revenue_year_cents'], 31250, 'Dashboard: Umsatz im Jahr');
same(count($dash['revenue_series']), 12, 'Dashboard: 12-Monats-Verlauf');
same($dash['receivables_cents'], 535, 'Dashboard: offene Forderungen');
check(isset($dash['stock_value_cents'], $dash['cash_cents'], $dash['payables_cents'], $dash['shipments_active']), 'Dashboard enthält alle Kennzahlen');
$cl = $A->get("/customers/{$cust['id']}");
same($cl['stats']['revenue_cents'], 31250, 'Kundenakte: Umsatz');
same($cl['stats']['open_cents'], 535, 'Kundenakte: offene Forderung');
$sv = $A->get('/reports/stock-value');
check($sv['total_cents'] > 0, 'Lagerwert-Auswertung');
check(count($A->get('/audit?limit=50')['rows']) > 10, 'Änderungsprotokoll wird geschrieben');

section('Mandantentrennung');
$B->ok('POST', '/auth/signup', ['company' => 'Fremdfirma GmbH', 'name' => 'Bernd Boss', 'email' => 'bernd@fremd.de', 'password' => 'AnderesPasswort77']);
same(count($B->get('/customers')['rows']), 0, 'Mandant B sieht keine Kunden von A');
same(count($B->get('/products')['rows']), 0, 'Mandant B sieht keine Artikel von A');
same(count($B->get('/sales/invoices')['rows']), 0, 'Mandant B sieht keine Rechnungen von A');
same(count($B->get('/accounting/journal')['rows']), 0, 'Mandant B sieht kein Journal von A');
same(count($B->get('/warehouses')['rows']), 1, 'Mandant B hat nur sein eigenes Lager');
$cust2B = $B->ok('POST', '/customers', ['name' => 'Kunde bei B']);
same($cust2B['number'], '10001', 'Mandant B startet mit eigenen Kontonummern');
$probe = [
    ["/customers/{$cust['id']}", 'Kunde'], ["/suppliers/{$sup['id']}", 'Lieferant'], ["/products/{$p1['id']}", 'Artikel'],
    ["/sales/invoices/{$invDraft['id']}", 'Rechnung'], ["/sales/orders/{$ord['id']}", 'Auftrag'], ["/sales/deliveries/{$del['id']}", 'Lieferschein'],
    ["/purchasing/orders/{$po['id']}", 'Bestellung'], ["/purchasing/invoices/{$si['id']}", 'Eingangsrechnung'], ["/accounting/journal/{$mj['id']}", 'Buchung'],
    ['/accounting/accounts/' . acct($A, '8400')['id'] . '/ledger', 'Kontoblatt'], ["/logistics/shipments/{$sh['id']}", 'Sendung'], ["/inventory/{$inv1['id']}", 'Inventur'],
    ["/customers/{$cust['id']}/statement", 'Kundenkonto'],
];
foreach ($probe as [$path, $what]) $B->fails('GET', $path, null, 404, "B kann $what von A nicht lesen");
$B->fails('PUT', "/customers/{$cust['id']}", ['name' => 'Gekapert'], 404, 'B kann Kunde von A nicht ändern');
$B->fails('DELETE', "/products/{$p3['id']}", null, 404, 'B kann Artikel von A nicht löschen');
$B->fails('POST', "/sales/invoices/{$invDraft['id']}/payments", ['amount_cents' => 1], 404, 'B kann keine Zahlung auf Rechnung von A buchen');
$B->fails('POST', "/payments/{$p['id']}/reverse", null, 404, 'B kann Zahlung von A nicht stornieren');
$B->fails('POST', "/sales/invoices/{$invDraft['id']}/credit-note", [], 404, 'B kann keine Gutschrift zu A erzeugen');
$B->fails('POST', '/sales/quotes', ['customer_id' => $cust['id'], 'lines' => [['description' => 'x', 'qty' => 1, 'price_cents' => 1]]], 400, 'B kann Kunde von A nicht in Beleg verwenden');
$B->fails('POST', '/sales/quotes', ['customer_id' => $cust2B['id'], 'lines' => [['product_id' => $p1['id'], 'qty' => 1]]], 400, 'B kann Artikel von A nicht in Beleg verwenden');
$B->fails('POST', '/stock/adjust', ['product_id' => $p1['id'], 'warehouse_id' => $wh1['id'], 'delta' => 5, 'reason' => 'x'], 404, 'B kann Bestand von A nicht ändern');
$B->fails('POST', '/accounting/transfer', ['from_account_id' => $bank['id'], 'to_account_id' => $cash['id'], 'amount_cents' => 1], 400, 'B kann Konten von A nicht bebuchen');
$B->fails('POST', '/accounting/journal', ['date' => "$year-01-01", 'text' => 'x', 'lines' => [['account_id' => $office['id'], 'debit_cents' => 5], ['account_id' => $cash['id'], 'credit_cents' => 5]]], 400, 'B kann Sachkonten von A nicht bebuchen');
same(count($A->get('/customers')['rows']), 2, 'A hat weiterhin seine 2 Kunden');
same(bal($A, '8400'), -30750, 'Erlöskonto von A unverändert');

section('Rollen, Tarif und Betreiber');
$A->ok('POST', '/users', ['name' => 'Vera Viewer', 'email' => 'vera@test-handel.de', 'password' => 'NurLesenPasswort1', 'role' => 'viewer']);
$A->ok('POST', '/users', ['name' => 'Walter Lager', 'email' => 'walter@test-handel.de', 'password' => 'LagerPasswort123', 'role' => 'warehouse']);
$A->fails('POST', '/users', ['name' => 'Vierter', 'email' => 'v4@test-handel.de', 'password' => 'ViertesPasswort12', 'role' => 'sales'], 409, 'Starter-Tarif erlaubt höchstens 3 Benutzer');
$A->fails('POST', '/users', ['name' => 'Schwach', 'email' => 'w@test-handel.de', 'password' => 'kurz', 'role' => 'sales'], 400, 'Benutzer mit schwachem Passwort');
$V = new Client($base);
$V->ok('POST', '/auth/login', ['email' => 'vera@test-handel.de', 'password' => 'NurLesenPasswort1']);
same(count($V->get('/customers')['rows']), 2, 'Nur-Lesen darf Kunden sehen');
$V->fails('POST', '/customers', ['name' => 'Nicht erlaubt'], 403, 'Nur-Lesen darf keine Kunden anlegen');
$V->fails('GET', '/accounting/journal', null, 403, 'Nur-Lesen sieht die Buchhaltung nicht');
$V->fails('GET', '/users', null, 403, 'Nur-Lesen sieht keine Benutzerverwaltung');
$V->fails('PUT', '/settings', ['company_name' => 'Hack'], 403, 'Nur-Lesen darf Einstellungen nicht ändern');
$V->fails('POST', "/sales/invoices/{$invDraft['id']}/payments", ['amount_cents' => 1], 403, 'Nur-Lesen darf keine Zahlung buchen');
check(!isset($V->get('/reports/dashboard')['cash_cents']), 'Dashboard zeigt Nur-Lesen keine Kontostände');
$W = new Client($base);
$W->ok('POST', '/auth/login', ['email' => 'walter@test-handel.de', 'password' => 'LagerPasswort123']);
$W->ok('POST', '/stock/adjust', ['product_id' => $p3['id'], 'warehouse_id' => $wh1['id'], 'delta' => 1, 'reason' => 'Fund']);
$W->fails('POST', '/sales/invoices', ['customer_id' => $cust['id'], 'lines' => [['description' => 'x', 'qty' => 1, 'price_cents' => 1]]], 403, 'Lager darf keine Rechnungen schreiben');
$op = ['X-Operator-Key' => 'test-operator-key-0123456789'];
[$s] = $anon->call('GET', '/operator/tenants');
same($s, 401, 'Betreiber-Konsole ohne Schlüssel');
[$s, $j] = $anon->call('GET', '/operator/tenants', null, $op);
check($s === 200 && count($j['rows']) === 2, 'Betreiber sieht beide Mandanten', $j);
[$s] = $anon->call('PUT', '/operator/tenants/1', ['plan' => 'business'], $op);
same($s, 200, 'Betreiber ändert Tarif');
$A->ok('POST', '/users', ['name' => 'Vierter', 'email' => 'v4@test-handel.de', 'password' => 'ViertesPasswort12', 'role' => 'sales']);
$A->ok('PUT', '/users/' . $A->get('/users')['rows'][1]['id'], ['active' => false]);
$A->fails('PUT', '/users/' . $me['user']['id'], ['role' => 'viewer'], 409, 'Administrator kann sich nicht selbst herabstufen');
[$s] = $anon->call('PUT', '/operator/tenants/2', ['active' => false], $op);
[$s2] = $B->call('GET', '/customers');
same($s2, 401, 'gesperrter Mandant kommt nicht mehr rein');

section('Weitere Sicherheits- und Randfälle');
[$s] = $V->call('GET', '/customers');
same($s, 401, 'gesperrter Benutzer verliert sofort den Zugriff');
$V->fails('POST', '/auth/login', ['email' => 'vera@test-handel.de', 'password' => 'NurLesenPasswort1'], 401, 'gesperrter Benutzer kann sich nicht anmelden');
$raw = function (string $ctype, string $body) use ($base, $A) {
    $ch = curl_init("$base/api/customers");
    curl_setopt_array($ch, [CURLOPT_POST => true, CURLOPT_POSTFIELDS => $body, CURLOPT_RETURNTRANSFER => true, CURLOPT_HTTPHEADER => ['X-Requested-With: erp', "Content-Type: $ctype", 'Cookie: ' . $A->cookie]]);
    curl_exec($ch);
    $st = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $st;
};
same($raw('text/plain', '{"name":"x"}'), 415, 'nur JSON wird angenommen');
same($raw('application/json', '{"name":"' . str_repeat('a', 1100000) . '"}'), 413, 'zu große Anfragen werden abgelehnt');
same($raw('application/json', '{kaputt'), 400, 'ungültiges JSON');
same(count($A->get('/customers?q=' . urlencode("' OR '1'='1"))['rows']), 0, 'SQL-Zeichen in der Suche sind harmlos');
same(count($A->get('/customers?q=' . urlencode('%'))['rows']), 0, 'Platzhalter in der Suche werden nicht als Platzhalter gedeutet');
$us = $A->ok('POST', '/customers', ['name' => 'Müller_Söhne 100% KG']);
same(count($A->get('/customers?q=' . urlencode('ller_S'))['rows']), 1, 'Suche nach Unterstrich findet den Eintrag');
same(count($A->get('/customers?q=' . urlencode('ller%S'))['rows']), 0, 'Prozentzeichen in der Suche ist kein Platzhalter');
same(count($A->get('/customers?q=' . urlencode('100%'))['rows']), 1, 'Suche nach Prozentzeichen findet den Eintrag');
$A->ok('DELETE', "/customers/{$us['id']}");
$A->fails('GET', '/sales/gibtsnicht', null, 404, 'unbekannte Belegart');
$A->fails('GET', '/gibtsnicht', null, 404, 'unbekannter Endpunkt');
$wegwerf = $A->ok('POST', '/customers', ['name' => '<script>alert(1)</script> Wegwerf']);
same($A->get("/customers/{$wegwerf['id']}")['item']['name'], '<script>alert(1)</script> Wegwerf', 'Sonderzeichen bleiben unverändert gespeichert (Ausgabe wird in der Oberfläche maskiert)');
$A->ok('DELETE', "/customers/{$wegwerf['id']}");
$A->fails('GET', "/customers/{$wegwerf['id']}", null, 404, 'gelöschter Kunde ist weg');
$A->fails('DELETE', "/customers/{$cust['id']}", null, 409, 'Kunde mit Belegen nicht löschbar');
// Betreiber legt Mandanten an (wenn die Selbstregistrierung ausgeschaltet ist)
[$s, $j] = $anon->call('POST', '/operator/tenants', ['company' => 'Betreiber-Firma', 'name' => 'Oskar Op', 'email' => 'oskar@betreiber.de', 'password' => 'BetreiberPasswort1', 'plan' => 'business'], $op);
same($s, 200, 'Betreiber legt Mandanten an');
[$s] = $anon->call('POST', '/operator/tenants', ['company' => 'X', 'name' => 'X', 'email' => 'x@betreiber.de', 'password' => 'BetreiberPasswort1'], ['X-Operator-Key' => 'falsch-falsch-falsch-falsch']);
same($s, 401, 'Betreiber-Funktion mit falschem Schlüssel');
$O = new Client($base);
$me2 = $O->ok('POST', '/auth/login', ['email' => 'oskar@betreiber.de', 'password' => 'BetreiberPasswort1']);
same($me2['tenant']['plan'], 'business', 'neuer Mandant hat den gewählten Tarif');
$A->ok('POST', '/auth/password', ['current' => 'GeheimesPasswort42', 'new' => 'NeuesPasswort987']);
$A->fails('POST', '/auth/password', ['current' => 'falsch', 'new' => 'NeuesPasswort987'], 400, 'Passwortwechsel mit falschem aktuellem Passwort');
$A2 = new Client($base);
$A2->fails('POST', '/auth/login', ['email' => 'anna@test-handel.de', 'password' => 'GeheimesPasswort42'], 401, 'altes Passwort gilt nicht mehr');
$A2->ok('POST', '/auth/login', ['email' => 'anna@test-handel.de', 'password' => 'NeuesPasswort987']);

section('Betrieb: Sicherung und Löschen eines Mandanten');
$cli = fn(string $script, string $args = '') => shell_exec('ERP_CONFIG=' . escapeshellarg((string) getenv('ERP_CONFIG_FOR_CLI')) . ' php ' . escapeshellarg(dirname(__DIR__) . "/tools/$script") . " $args 2>&1");
$before = count($anon->call('GET', '/operator/tenants', null, $op)[1]['rows']);
$out = $cli('delete-tenant.php', '2');
check(str_contains((string) $out, '--yes'), 'Löschen verlangt eine ausdrückliche Bestätigung', $out);
$out = $cli('delete-tenant.php', '2 --yes');
check(str_contains((string) $out, 'gelöscht'), 'Mandant wird gelöscht', $out);
$after = $anon->call('GET', '/operator/tenants', null, $op)[1]['rows'];
same(count($after), $before - 1, 'Mandant ist aus der Liste verschwunden');
same($B->call('GET', '/customers')[0], 401, 'Sitzungen des gelöschten Mandanten sind ungültig');
if (($GLOBALS['driver'] ?? 'sqlite') === 'sqlite') {
    $dir = sys_get_temp_dir() . '/erp-backup-test-' . getmypid();
    $out = $cli('backup.php', escapeshellarg($dir));
    check(str_contains((string) $out, 'Sicherung erstellt'), 'SQLite-Sicherung', $out);
    foreach (glob("$dir/*") ?: [] as $f) unlink($f);
    @rmdir($dir);
}
